# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c14385254c4d1c7adca3cfb47a219831f9a460f8ba2e1e385b7ab5e966b13203b60a3601c33806c3e6d7b035410cb9f946f504a188cfb9464708857dc62f3b

test:
  secret_key_base: bf5a0863493aa2ba4a43d5e91c0c222ef0222d6badd897d96c6e385ff9502ad0116a3f2233b90bf6efb1bd47903d3e49ff0317c1d43ae2860b8abcc0763676e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
